### ISSUE TITLE
Hash value is sometimes negative

### ISSUE THREAD

**Issue by kdeenanauth** [emluque/dscache#2]
I am very happy with the dscache API. However, sometimes the `defaultGetBucketNumber` can result in a negative value (which results in `runtime error: index out of range`)

See demo at:
https://play.golang.org/p/BV2NMCZ5Drt

Example with dscache:
```go
package main

import (
	"time"

	"github.com/emluque/dscache"
)

func main() {
	ds, _ := dscache.New(200 * dscache.MB)
	ds.Set("token:WXRKoUkig", "5", 1*time.Hour)
}
```

Results in:
```panic: runtime error: index out of range

goroutine 1 [running]:
github.com/emluque/dscache.(*Dscache).Set(0xc04204e080, 0x4b5e47, 0xf, 0x4b42f9, 0x1, 0x34630b8a000, 0xc042071f78, 0xc042044058)
        C:/Users/kevin/Documents/git/go/src/github.com/emluque/dscache/dscache.go:142 +0xd2
main.main()
        C:/Users/kevin/Documents/git/go/src/gitlab.com/kdeenanauth/dscache-test/dscache-test.go:11 +0x78```

**Comment by emluque** [comment]
Hi @kdeenanauth , I know you have submitted this issue more than 6 months ago. I'm sorry I didn't reply sooner, but honestly github for some reason didn't send me a notification when you submitted the issue. I guess by now you have moved on and used another library, I copied the hash function from an article that compared different hash functions for strings. I promise you I will look into the issue this week. 

Best regards, and sorry I didn't reply, but I never got notified when the issue was created.

**Comment by ghost** [comment]
Hi @kdeenanauth . I just fixed the issue. Thank you for reporting it. Again I'm really sorry I was not able to fix it before, but I really didn't got any sort of notification when the issue was reported,

**Comment by kdeenanauth** [comment]
Hey @emluque - it's no problem! Thanks for fixing it!

I had switched to https://github.com/karlseguin/ccache but I still like the dscache API better so I might switch back
